version: "3.8"
services:
  redis:
    image: redis
    command: redis-server /home/simpleuser/12_factor_app/redis.conf
    volumes:
      - /home/simpleuser/12_factor_app/redis.conf:/home/alex/12_factor_app/redis.conf

  app:
    build:
      context: /home/simpleuser/12_factor_app/
    env_file:
      - /home/simpleuser/12_factor_app/.env
    restart: unless-stopped
    ports: 
      - 10000:10000
