name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: install lib 
        run: sudo apt install sshpass

      
      - name: Deploy to Hosting
        run: sshpass -p 87654321 ssh -oStrictHostKeyChecking=no simpleuser@149.154.71.129 -t "pip install --upgrade pip && cd 12_factor_app && git pull && docker compose down && docker compose up --build -d && exit"
        
